### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by yleaxeman**
Updated to @folkehelseinstituttet/style v3.2.3

### CODE REVIEW

**Review by proand — COMMENTED** [review]
Build fails...
I believe [Azure/static-web-apps-deploy@v0.0.1-preview](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/blob/19f7aff72e25fa47cd98faae200e35e77c582613/.github/workflows/azure-static-web-apps-salmon-hill-00d855003.yml#L23) must be updated...
See https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#build-configuration for more info

**Comment by yleaxeman** [comment]
> Build fails... I believe [Azure/static-web-apps-deploy@v0.0.1-preview](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/blob/19f7aff72e25fa47cd98faae200e35e77c582613/.github/workflows/azure-static-web-apps-salmon-hill-00d855003.yml#L23) must be updated... See https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#build-configuration for more info

Strange. Never needed that before.

**Comment by yleaxeman** [comment]
> > Build fails... I believe [Azure/static-web-apps-deploy@v0.0.1-preview](https://github.com/folkehelseinstituttet/Fhi.Frontend.Demo/blob/19f7aff72e25fa47cd98faae200e35e77c582613/.github/workflows/azure-static-web-apps-salmon-hill-00d855003.yml#L23) must be updated... See https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#build-configuration for more info
> 
> Strange. Never needed that before.

Just needed to state same version number as in package.json (0.11.1)

**Review by proand — APPROVED** [review]
Good to go 👍

**Pull request merged**
